source 'https://rubygems.org'

gem 'rails', '4.2.0'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

# gem "strong_parameters"


#gem 'sqlite3'
gem 'mysql2'
gem 'pg'
gem 'will_paginate', '~> 3.0.6'
gem "bcrypt-ruby", :require => "bcrypt"

# Gems used only for assets and not required
# in production environments by default.

gem 'sass-rails',   '~> 5.0'
gem 'coffee-rails', '~> 4.1.0'

gem 'bootstrap-sass', '~> 3.2'

# gem 'twitter-bootstrap-rails'
# gem 'therubyracer'
# gem 'less-rails'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
#gem 'therubyracer', :platforms => :ruby

gem 'uglifier', '>= 1.3.0'

gem 'jquery-fileupload-rails', '= 0.4.1'

gem 'simple_form'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'thin'

gem  'paperclip', '~> 4.2'

group :development, :test do
  gem 'rspec-rails', '~> 3.0'
  gem 'quiet_assets'
  gem 'database_cleaner'
  gem 'factory_girl_rails'

end
# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'

