source 'https://rubygems.org'

gem 'rails', '3.2.13'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

#gem 'sqlite3'
gem 'mysql2'
gem 'pg'
gem 'will_paginate', '~> 3.0.6'
gem "bcrypt-ruby", :require => "bcrypt"

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  
  gem 'bootstrap-sass', '=3.1.1.0'

 # gem 'twitter-bootstrap-rails'
 # gem "therubyracer"
 # gem "less-rails"

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  #gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
  gem 'jquery-fileupload-rails'
end

gem 'simple_form'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'thin'

gem  "paperclip", "~> 4.2"

group :development, :test do
  gem 'rspec-rails', '~> 3.0'
  gem 'quiet_assets'
  gem 'database_cleaner'
  gem 'factory_girl_rails'

end
# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'

